language: node_js
node_js:
  - 12
services:
  - docker
install:
  - npm i macaca-ecosystem
  - npm i vuepress -g
  - vuepress build docs
script:
  - npm i
  - $(npm bin)/macaca-ecosystem push --cwd ./docs_dist --branch gh-pages
  - npm run lint
  - docker run -it --entrypoint=bash -v `pwd`:/root/tmp --rm macacajs/macaca-electron-docker-ubuntu -c "cd /root/tmp && sh /root/entrypoint.sh && sleep 3 && npm run test-cov"
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
