language: node_js
node_js:
  - 8
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1366x768x24 > /dev/null 2>&1 &
  - npm i macaca-ecosystem
  - npm i vuepress -g
  - vuepress build docs
script:
  - npm i
  - $(npm bin)/macaca-ecosystem push --cwd ./docs_dist --branch gh-pages
  - npm run lint
  - npm run test-cov
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
