language: node_js
node_js:
  - 8
addons:
  apt:
    packages:
      - xvfb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1366x768x24 > /dev/null 2>&1 &
  - yarn add vuepress macaca-ecosystem
  - npm run docs:build
script:
  - npm i
  - $(npm bin)/macaca-ecosystem push --cwd ./docs_dist --branch gh-pages
  - npm run lint
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
